"""Append-only decision audit package."""

from omra.audit.errors import (
    AuditError,
    AuditReadError,
    AuditValidationError,
    AuditWriteError,
)
from omra.audit.events import (
    PAYLOAD_MODELS,
    Actor,
    AuditEvent,
    AuditPayload,
    BlockedBy,
    BudgetConsumedPayload,
    CanaryStepPayload,
    CassetteSmokePayload,
    ConfigChangedPayload,
    ConfigKeyDiff,
    Correlation,
    CounterfactualOrder,
    EventType,
    FxSnapshotAppliedPayload,
    GuardVerdictPayload,
    LlmCallPayload,
    OrderFilledPayload,
    OrderIoPayload,
    PlanCreatedPayload,
    PlanDecisionPayload,
    ProtectionTrippedPayload,
    ReconcileWhitelistedPayload,
    RollbackFiredPayload,
    RpcCommandPayload,
    StateTransitionPayload,
    SurveillanceTransitionPayload,
    TargetsComputedPayload,
    TokenIssuedPayload,
    TrackingErrorComponent,
    UnmatchedFillPayload,
    payload_model_for,
    tracking_error_component,
)
from omra.audit.logger import AuditLogger
from omra.audit.reader import iter_audit_file, read_audit_line

__all__ = [
    "PAYLOAD_MODELS",
    "Actor",
    "AuditError",
    "AuditEvent",
    "AuditLogger",
    "AuditPayload",
    "AuditReadError",
    "AuditValidationError",
    "AuditWriteError",
    "BlockedBy",
    "BudgetConsumedPayload",
    "CanaryStepPayload",
    "CassetteSmokePayload",
    "ConfigChangedPayload",
    "ConfigKeyDiff",
    "Correlation",
    "CounterfactualOrder",
    "EventType",
    "FxSnapshotAppliedPayload",
    "GuardVerdictPayload",
    "LlmCallPayload",
    "OrderFilledPayload",
    "OrderIoPayload",
    "PlanCreatedPayload",
    "PlanDecisionPayload",
    "ProtectionTrippedPayload",
    "ReconcileWhitelistedPayload",
    "RollbackFiredPayload",
    "RpcCommandPayload",
    "StateTransitionPayload",
    "SurveillanceTransitionPayload",
    "TargetsComputedPayload",
    "TokenIssuedPayload",
    "TrackingErrorComponent",
    "UnmatchedFillPayload",
    "iter_audit_file",
    "payload_model_for",
    "read_audit_line",
    "tracking_error_component",
]
