"""create initial SQLite schema

Revision ID: 0001_sqlite_schema
Revises:
Create Date: 2026-08-19 08:24:24.765162
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_sqlite_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:  # noqa: PLR0915
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("subject_key", sa.Text(), nullable=True),
        sa.Column("account_id", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.Text(), nullable=False),
        sa.Column("grace_deadline", sa.Text(), nullable=True),
        sa.Column("timeout_action", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('PENDING','APPROVED','REJECTED','EXPIRED','ESCALATED','CANCELLED')",
            name=op.f("ck_approval_requests_state_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requests")),
    )
    op.create_index(
        "ix_approvals_open",
        "approval_requests",
        ["state", "grace_deadline"],
        unique=False,
        sqlite_where=sa.text("state = 'PENDING'"),
    )
    op.create_table(
        "bot_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("safe_mode_reasons", sa.Text(), nullable=True),
        sa.Column("since", sa.Text(), nullable=False),
        sa.Column("prev_state", sa.Text(), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_bot_state_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_state")),
    )
    op.create_table(
        "broker_tokens",
        sa.Column("broker", sa.Text(), nullable=False),
        sa.Column("env", sa.Text(), nullable=False),
        sa.Column("credential_id", sa.Text(), server_default=sa.text("'*'"), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "broker IN ('kis','upbit')", name=op.f("ck_broker_tokens_broker_values")
        ),
        sa.CheckConstraint("env IN ('live','paper')", name=op.f("ck_broker_tokens_env_values")),
        sa.CheckConstraint(
            "kind IN ('access_token','approval_key')", name=op.f("ck_broker_tokens_kind_values")
        ),
        sa.PrimaryKeyConstraint(
            "broker", "env", "credential_id", "kind", name=op.f("pk_broker_tokens")
        ),
    )
    op.create_table(
        "canary_state",
        sa.Column("change_id", sa.Text(), nullable=False),
        sa.Column("target_kind", sa.Text(), nullable=False),
        sa.Column("ladder_json", sa.Text(), nullable=False),
        sa.Column("step_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("alpha_current", sa.Text(), nullable=False),
        sa.Column("step_started_on", sa.Text(), nullable=False),
        sa.Column("w_champion_ref", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("veto_deadline", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('ACTIVE','DONE','ROLLED_BACK')", name=op.f("ck_canary_state_state_values")
        ),
        sa.CheckConstraint(
            "target_kind IN ('targets','methodology','universe_swap')",
            name=op.f("ck_canary_state_target_kind_values"),
        ),
        sa.PrimaryKeyConstraint("change_id", name=op.f("pk_canary_state")),
    )
    op.create_table(
        "change_budget",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.Text(), nullable=False),
        sa.Column("cap", sa.Integer(), nullable=False),
        sa.Column("consumed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "bucket IN ('total','targets','params','logic')",
            name=op.f("ck_change_budget_bucket_values"),
        ),
        sa.PrimaryKeyConstraint("year", "bucket", name=op.f("pk_change_budget")),
    )
    op.create_table(
        "contribution_ledger",
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("ytd_paid_krw", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("as_of", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "source IN ('api','csv','manual')", name=op.f("ck_contribution_ledger_source_values")
        ),
        sa.PrimaryKeyConstraint("account_id", "year", name=op.f("pk_contribution_ledger")),
    )
    op.create_table(
        "execution_state",
        sa.Column("run_date", sa.Text(), nullable=False),
        sa.Column("venue", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), server_default=sa.text("'*'"), nullable=False),
        sa.Column("counter_kind", sa.Text(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "run_date", "venue", "instrument_key", "counter_kind", name=op.f("pk_execution_state")
        ),
    )
    op.create_table(
        "experiments",
        sa.Column("experiment_id", sa.Text(), nullable=False),
        sa.Column("spec_hash", sa.Text(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("primary_metric", sa.Text(), nullable=True),
        sa.Column("secondary_metrics", sa.Text(), nullable=True),
        sa.Column("stop_conditions", sa.Text(), nullable=True),
        sa.Column("sample_from", sa.Text(), nullable=False),
        sa.Column("sample_to", sa.Text(), nullable=False),
        sa.Column("registered_at", sa.Text(), nullable=False),
        sa.Column("registered_by", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("experiment_id", name=op.f("pk_experiments")),
    )
    op.create_index("ix_experiments_hash", "experiments", ["spec_hash"], unique=False)
    op.create_table(
        "harvest_ledger",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "order_amount_krw_cum", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "realized_target_krw_cum", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("year", name=op.f("pk_harvest_ledger")),
    )
    op.create_table(
        "market_holidays",
        sa.Column("venue", sa.Text(), nullable=False),
        sa.Column("cal_date", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("is_open", sa.Integer(), nullable=False),
        sa.Column("session_note", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "source IN ('exchange_calendars','kis_tr')",
            name=op.f("ck_market_holidays_source_values"),
        ),
        sa.PrimaryKeyConstraint("venue", "cal_date", "source", name=op.f("pk_market_holidays")),
    )
    op.create_table(
        "nav_snapshots",
        sa.Column("snap_date", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("nav_krw", sa.Integer(), nullable=False),
        sa.Column("cash_krw", sa.Integer(), nullable=False),
        sa.Column("positions_json", sa.Text(), nullable=False),
        sa.Column("fx_usdkrw", sa.Text(), nullable=True),
        sa.Column("frozen_reserve_krw", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("snap_date", "account_id", name=op.f("pk_nav_snapshots")),
    )
    op.create_table(
        "notification_suppression",
        sa.Column("subject_key", sa.Text(), nullable=False),
        sa.Column("reason_key", sa.Text(), nullable=False),
        sa.Column("last_sent_date", sa.Text(), nullable=False),
        sa.Column("last_sent_at", sa.Text(), nullable=False),
        sa.Column("send_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "subject_key", "reason_key", name=op.f("pk_notification_suppression")
        ),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("broker_order_id", sa.Text(), nullable=True),
        sa.Column("broker_order_org_no", sa.Text(), nullable=True),
        sa.Column("orig_broker_order_id", sa.Text(), nullable=True),
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("order_type", sa.Text(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("qty", sa.Text(), nullable=False),
        sa.Column("limit_price", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("plan_id", sa.Text(), nullable=True),
        sa.Column("reprice_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("submitted_at_kst", sa.Text(), nullable=True),
        sa.Column("dry_run", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "broker_order_id", "account_id", name=op.f("uq_orders_broker_order_id")
        ),
    )
    op.create_index("ix_orders_intent", "orders", ["intent", "submitted_at_kst"], unique=False)
    op.create_index(
        "ix_orders_netbuy", "orders", ["submitted_at_kst", "side", "status"], unique=False
    )
    op.create_index(
        "ix_orders_open",
        "orders",
        ["account_id", "status"],
        unique=False,
        sqlite_where=sa.text("status IN ('SUBMITTING','PENDING','PARTIALLY_FILLED')"),
    )
    op.create_index(
        "ix_orders_orphan",
        "orders",
        ["account_id", "instrument_key", "side", "submitted_at_kst"],
        unique=False,
        sqlite_where=sa.text("status IN ('SUBMITTING','EXPIRED_UNKNOWN')"),
    )
    op.create_index("ix_orders_plan", "orders", ["plan_id"], unique=False)
    op.create_table(
        "pending_tax_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("risk_type", sa.Text(), nullable=False),
        sa.Column("abol_date", sa.Text(), nullable=False),
        sa.Column("cross_checked", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('OPEN','CONSUMED','EXPIRED')",
            name=op.f("ck_pending_tax_events_state_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_tax_events")),
        sa.UniqueConstraint(
            "instrument_key",
            "risk_type",
            "abol_date",
            name=op.f("uq_pending_tax_events_instrument_key"),
        ),
    )
    op.create_table(
        "pending_transfers",
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("abol_date", sa.Text(), nullable=False),
        sa.Column("substitute_key", sa.Text(), nullable=False),
        sa.Column("total_qty", sa.Integer(), nullable=False),
        sa.Column("slices_total", sa.Integer(), nullable=False),
        sa.Column("slices_done", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('PENDING','RUNNING','DONE','ABORTED')",
            name=op.f("ck_pending_transfers_state_values"),
        ),
        sa.PrimaryKeyConstraint("account_id", "instrument_key", name=op.f("pk_pending_transfers")),
    )
    op.create_table(
        "policy_versions",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Text(), nullable=False),
        sa.Column("inputs_hash", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('targets','universe')", name=op.f("ck_policy_versions_kind_values")
        ),
        sa.PrimaryKeyConstraint("kind", "version", name=op.f("pk_policy_versions")),
    )
    op.create_table(
        "portfolio_decomposition",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("sub_alloc_krw", sa.Text(), nullable=False),
        sa.Column("is_legacy", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint(
            "version", "account_id", "instrument_key", name=op.f("pk_portfolio_decomposition")
        ),
    )
    op.create_table(
        "portfolio_decomposition_meta",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Text(), nullable=False),
        sa.Column("v_total_at_save", sa.Text(), nullable=False),
        sa.Column("v_a_at_save_json", sa.Text(), nullable=False),
        sa.Column("targets_capped_json", sa.Text(), nullable=False),
        sa.Column("targets_version", sa.Integer(), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_portfolio_decomposition_meta")),
    )
    op.create_index("ix_decomp_meta_asof", "portfolio_decomposition_meta", ["as_of"], unique=False)
    op.create_table(
        "positions",
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("qty", sa.Text(), nullable=False),
        sa.Column("avg_cost", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("account_id", "instrument_key", name=op.f("pk_positions")),
    )
    op.create_table(
        "presence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("last_seen_at", sa.Text(), nullable=False),
        sa.Column("declared_away", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("away_until", sa.Text(), nullable=True),
        sa.Column("since", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('NORMAL','AWAY_SOFT','AWAY','AWAY_LONG')",
            name=op.f("ck_presence_state_values"),
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_presence_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_presence")),
    )
    op.create_table(
        "protection_counters",
        sa.Column("breaker_id", sa.Text(), nullable=False),
        sa.Column("run_date", sa.Text(), nullable=False),
        sa.Column("scope_key", sa.Text(), server_default=sa.text("'*'"), nullable=False),
        sa.Column("counter_kind", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "breaker_id",
            "run_date",
            "scope_key",
            "counter_kind",
            name=op.f("pk_protection_counters"),
        ),
    )
    op.create_table(
        "protection_state",
        sa.Column("breaker_id", sa.Text(), nullable=False),
        sa.Column("scope_key", sa.Text(), server_default=sa.text("'*'"), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("grade", sa.Text(), nullable=False),
        sa.Column("tripped_at", sa.Text(), nullable=True),
        sa.Column("cleared_at", sa.Text(), nullable=True),
        sa.Column("reason_json", sa.Text(), nullable=True),
        sa.Column("counters_json", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "grade IN ('A','B','B_STAR','C')", name=op.f("ck_protection_state_grade_values")
        ),
        sa.CheckConstraint(
            "status IN ('ARMED','TRIPPED')", name=op.f("ck_protection_state_status_values")
        ),
        sa.PrimaryKeyConstraint("breaker_id", "scope_key", name=op.f("pk_protection_state")),
    )
    op.create_index(
        "ix_prot_tripped",
        "protection_state",
        ["status", "breaker_id"],
        unique=False,
        sqlite_where=sa.text("status = 'TRIPPED'"),
    )
    op.create_table(
        "rebalance_plans",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("as_of_kst", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("sleeve_id", sa.Text(), nullable=True),
        sa.Column("expected_turnover", sa.Text(), nullable=False),
        sa.Column("sanity_json", sa.Text(), nullable=False),
        sa.Column("approved", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("approved_at", sa.Text(), nullable=True),
        sa.Column("rejected_at", sa.Text(), nullable=True),
        sa.Column("targets_version", sa.Integer(), nullable=True),
        sa.Column("universe_version", sa.Integer(), nullable=True),
        sa.Column("inputs_hash", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rebalance_plans")),
    )
    op.create_index("ix_plans_asof", "rebalance_plans", ["as_of_kst"], unique=False)
    op.create_table(
        "reconcile_expectations",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), nullable=True),
        sa.Column("expected_date_from", sa.Text(), nullable=False),
        sa.Column("expected_date_to", sa.Text(), nullable=False),
        sa.Column("expected_qty", sa.Integer(), nullable=True),
        sa.Column("expected_amount", sa.Integer(), nullable=True),
        sa.Column("amount_tolerance", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("consumed_at", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('cash_in','cash_out','fill','scheduled_fill','ca_qty','fx_resettle','orphan_order')",  # noqa: E501
            name=op.f("ck_reconcile_expectations_kind_values"),
        ),
        sa.CheckConstraint(
            "source IN ('external_schedule','master_diff','ksdinfo','broker_fx','broker_dividend','system','instruction')",  # noqa: E501
            name=op.f("ck_reconcile_expectations_source_values"),
        ),
        sa.CheckConstraint(
            "amount_tolerance > 0", name=op.f("ck_reconcile_expectations_positive_tolerance")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconcile_expectations")),
    )
    op.create_index(
        "ix_reconcile_open",
        "reconcile_expectations",
        ["account_id", "kind", "expected_date_from"],
        unique=False,
        sqlite_where=sa.text("consumed_at IS NULL"),
    )
    op.create_table(
        "research_extractions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_grade", sa.Text(), nullable=False),
        sa.Column("published_at", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("layer", sa.Text(), nullable=False),
        sa.Column("decay_type", sa.Text(), nullable=True),
        sa.Column("affected_docs", sa.Text(), nullable=False),
        sa.Column("affected_params", sa.Text(), nullable=False),
        sa.Column("quoted_numbers", sa.Text(), nullable=False),
        sa.Column("flags", sa.Text(), nullable=False),
        sa.Column("conflicts_with_ours", sa.Text(), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("reject_rule", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "decay_type IN ('dep','api','law','evidence')",
            name=op.f("ck_research_extractions_decay_type_values"),
        ),
        sa.CheckConstraint(
            "layer IN ('T0','T1','T2','T3')", name=op.f("ck_research_extractions_layer_values")
        ),
        sa.CheckConstraint(
            "source_grade IN ('official','vendor','preprint','blog')",
            name=op.f("ck_research_extractions_source_grade_values"),
        ),
        sa.CheckConstraint(
            "verdict IN ('REVIEW','REJECT')", name=op.f("ck_research_extractions_verdict_values")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_extractions")),
        sa.UniqueConstraint("payload_hash", name=op.f("uq_research_extractions_payload_hash")),
    )
    op.create_index(
        "ix_research_verdict", "research_extractions", ["verdict", "collected_at"], unique=False
    )
    op.create_table(
        "run_ledger",
        sa.Column("run_date", sa.Text(), nullable=False),
        sa.Column("venue", sa.Text(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','running','done','skipped','failed')",
            name=op.f("ck_run_ledger_status_values"),
        ),
        sa.PrimaryKeyConstraint("run_date", "venue", "task_name", name=op.f("pk_run_ledger")),
    )
    op.create_table(
        "satellite_state",
        sa.Column("sub_sleeve_id", sa.Text(), nullable=False),
        sa.Column("lookback_months", sa.Integer(), nullable=False),
        sa.Column("current_holding_key", sa.Text(), nullable=True),
        sa.Column("stage_pct", sa.Text(), nullable=False),
        sa.Column("last_eval_date", sa.Text(), nullable=True),
        sa.Column("peak_krw", sa.Text(), nullable=False),
        sa.Column("dd_stage", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("dd_entered_at", sa.Text(), nullable=True),
        sa.Column("cooldown_until", sa.Text(), nullable=True),
        sa.Column("carryover_pct", sa.Text(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("ytd_turnover_pct", sa.Text(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("sub_sleeve_id", name=op.f("pk_satellite_state")),
    )
    op.create_table(
        "sleeve_state",
        sa.Column("sleeve_id", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("since", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("sleeve_id", name=op.f("pk_sleeve_state")),
    )
    op.create_table(
        "surveillance_flags",
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("risk_type", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.Text(), nullable=True),
        sa.Column("deadline_at", sa.Text(), nullable=True),
        sa.Column("override_level", sa.Integer(), nullable=True),
        sa.Column("override_expires_at", sa.Text(), nullable=True),
        sa.Column("override_actor", sa.Text(), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "state IN ('ACTIVE','RESOLVED','UNRESOLVED','FALSE_POSITIVE')",
            name=op.f("ck_surveillance_flags_state_values"),
        ),
        sa.PrimaryKeyConstraint(
            "instrument_key", "risk_type", "source", name=op.f("pk_surveillance_flags")
        ),
    )
    op.create_index(
        "ix_survflags_active",
        "surveillance_flags",
        ["instrument_key", "state", "effective_from"],
        unique=False,
    )
    op.create_table(
        "taxbase_snapshots",
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("as_of", sa.Text(), nullable=False),
        sa.Column("taxbase_price", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("instrument_key", "as_of", name=op.f("pk_taxbase_snapshots")),
    )
    op.create_table(
        "unmatched_fills",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("qty", sa.Text(), nullable=False),
        sa.Column("price", sa.Text(), nullable=False),
        sa.Column("filled_at_kst", sa.Text(), nullable=False),
        sa.Column("broker_exec_id", sa.Text(), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.Text(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('PENDING','ABSORBED','DISCARDED')",
            name=op.f("ck_unmatched_fills_state_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unmatched_fills")),
        sa.UniqueConstraint("broker_exec_id", name=op.f("uq_unmatched_fills_broker_exec_id")),
    )
    op.create_index(
        "ix_unmatched_open",
        "unmatched_fills",
        ["account_id", "state", "filled_at_kst"],
        unique=False,
        sqlite_where=sa.text("state = 'PENDING'"),
    )
    op.create_table(
        "experiment_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("experiment_id", sa.Text(), nullable=False),
        sa.Column("event_kind", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "event_kind IN ('registered','run_started','run_finished','gate_passed','gate_failed','promoted','rolled_back','frozen')",  # noqa: E501
            name=op.f("ck_experiment_events_event_kind_values"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.experiment_id"],
            name=op.f("fk_experiment_events_experiment_id_experiments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_events")),
    )
    op.create_index(
        "ix_expev_exp", "experiment_events", ["experiment_id", "created_at"], unique=False
    )
    op.create_table(
        "fills",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("qty", sa.Text(), nullable=False),
        sa.Column("price", sa.Text(), nullable=False),
        sa.Column("fee", sa.Text(), nullable=True),
        sa.Column("tax", sa.Text(), nullable=True),
        sa.Column("filled_at_kst", sa.Text(), nullable=False),
        sa.Column("settle_date", sa.Text(), nullable=False),
        sa.Column("broker_exec_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("broker_exec_id", name=op.f("uq_fills_broker_exec_id")),
    )
    op.create_index("ix_fills_order", "fills", ["order_id"], unique=False)
    op.create_index("ix_fills_settle", "fills", ["settle_date"], unique=False)
    op.create_table(
        "tax_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("instrument_key", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("amount_krw", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Text(), nullable=True),
        sa.Column("settle_date", sa.Text(), nullable=False),
        sa.Column("fx_rate", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("fill_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('realized_pnl','dividend','distribution','interest','withholding','redemption')",  # noqa: E501
            name=op.f("ck_tax_events_kind_values"),
        ),
        sa.CheckConstraint(
            "source IN ('broker_032','period_rights','computed','manual')",
            name=op.f("ck_tax_events_source_values"),
        ),
        sa.ForeignKeyConstraint(
            ["fill_id"], ["fills.id"], name=op.f("fk_tax_events_fill_id_fills")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_events")),
    )
    op.create_index(
        "ix_taxev_year", "tax_events", ["account_id", "settle_date", "kind"], unique=False
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_reconcile_idem ON reconcile_expectations (source, account_id, kind, ifnull(instrument_key,''), expected_date_from)"  # noqa: E501
    )
    op.execute(
        "CREATE TRIGGER trg_experiments_no_update BEFORE UPDATE ON experiments BEGIN SELECT RAISE(ABORT, 'experiments is append-only'); END"  # noqa: E501
    )
    op.execute(
        "CREATE TRIGGER trg_experiments_no_delete BEFORE DELETE ON experiments BEGIN SELECT RAISE(ABORT, 'experiments is append-only'); END"  # noqa: E501
    )
    op.execute(
        "CREATE TRIGGER trg_expev_no_update BEFORE UPDATE ON experiment_events BEGIN SELECT RAISE(ABORT, 'experiment_events is append-only'); END"  # noqa: E501
    )
    op.execute(
        "CREATE TRIGGER trg_expev_no_delete BEFORE DELETE ON experiment_events BEGIN SELECT RAISE(ABORT, 'experiment_events is append-only'); END"  # noqa: E501
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("restore via Litestream — 01 §1.3")
